version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    depends_on:
      - db
    environment:
      - APP_ENV=production
  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - static-data:/vol/static
  db:
    image: postgres:13-alpine
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/val/lib/postgresql/data
    environment:
      - POSTGRES_DB=digishop
      - POSTGRES_USER=digishop
      - POSTGRES_PASSWORD=Mkh81@77
volumes:
  static-data:
  postgres-data: